sensor 1 "Living Room" TEMPERATURE 10 min=-10 max=50
sensor 2 "Basement" HUMIDITY calibration=1.02
sensor 3 "Kitchen" TEMPERATURE 3 min=-10 max=50
sensor 4 "Library" HUMIDITY calibration=1.04
5 sensor "Basement" HUMIDITY 150 calibration=1.02
sensor 6  "Living Room" TEMPERATURE min=-10 max=50